POST http://localhost:3000/users/login
Content-Type: application/json
# Authorization: Bearer

{

    "email": "eracles@gamil.com",
    "password": "1234"
}

###

GET http://localhost:3000/home

###

POST http://localhost:3000/movies/createMovie
Content-Type: application/json

{
    "name" : "Superman",
    "description": "Superman es un superheroe que fue enviado a la tierra hace muchos años por la destruccion de su planeta y ha llegado a la tierra para salvarla de la maldad",
    "duration" : 210,
    "clasification" : "B"
}

###

POST http://localhost:3000/showtimes/create-showtime
Content-Type: application/json

{
    "roomId": 1,
    "movieId": 2,
    "datetime": "2025-08-19 18:30:00"
}

###
GET http://localhost:3000/showtimes/get-all
