POST http://localhost:3000/users/login
Content-Type: application/json
# Authorization: Bearer

{

    "email": "eracles@gamil.com",
    "password": "1234"
}

###

GET http://localhost:3000/movies/1

###

POST http://localhost:3000/movies/createMovie
Content-Type: application/json

{
    "name" : "Batman",
    "description": "Batman es un niño que pierde a sus padres tras el asesinato de los mismos, batman se propone a buscar al asesino convirtiendose en el caballero de la noche, Batman",
    "duration" : 220,
    "clasification" : "C"
}

###

POST http://localhost:3000/showtimes/create-showtime
Content-Type: application/json

{
    "roomId": 1,
    "movieId": 2,
    "datetime": "2025-08-22 20:30:00"
}

###
GET http://localhost:3000/showtimes/get-all

###
GET http://localhost:3000/showtimes/9


### 
POST http://localhost:3000/reservations/create-reservation
Content-Type: application/json

{
    "id_showtime": 1, 
    "id_user": 1, 
    "id_seat": 1, 
    "id_room": 1
}